# name: publish to npm
# 
# on:
#   push:
#     branches: [ master ]
# 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - uses: actions/checkout@v2
# 
#     - name: Use Node.js 12
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12
# 
#     - run: |
#             npm test
#             npm ci
#       env:
#         CI: true
#         
#     - name: setup npm config
#       run: |
#             echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_APIKEY }}" > .npmrc
#             npm config set scope criipto
#             npm version "1.6.$GITHUB_RUN_NUMBER"
#       working-directory: dist/
#     - name: push to npmjs
#       run: npm publish --access public

name: Bump version
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: |
            npm test
            npm ci
      env:
        CI: true

  tag:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true

  publish:
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - name: test print tag
      run: echo ${{needs.tag.outputs.new_tag}}
        #- name: Use Node.js 12
        #  uses: actions/setup-node@v1
        #  with:
        #    node-version: 12
        #- name: ci
        #run: npm ci
        #env:
        #CI: true
        #
        #- name: setup npm config
        #run: |
        #      echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_APIKEY }}" > .npmrc
        #      npm config set scope criipto
        #      npm version ${{needs.tag.outputs.new_tag}}
        #working-directory: dist/
        #
        #- name: push to npmjs
        #run: npm publish --access public
        #continue-on-error: true
